/*
 * generated by Xtext 2.25.0
 */
package com.mike.berezhkov.huawei.tests

import com.google.inject.Inject
import com.mike.berezhkov.huawei.cPoCP.Model
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(CPoCPInjectorProvider)
class CPoCPParsingTest {
	@Inject
	ParseHelper<Model> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Courses:
				Math,
				Physics,
				Chemistry,
				Biology
				
			Students:
				Ivanov,
				Petrov,
				Sidorov
				
			Scores:
				Ivanov: { //references student, listed in “Students” section
					Math: 5,4,5,4,3,3,5; //references course, listed in “Courses” section
					Physics: 3,2,4,5;
					Chemistry:5,5,4,3;
				},
				Petrov: { //references student, listed in “Students” section
					Biology: 5,4,5,4,3,3,5; //references course, listed in “Courses” section
					Physics: 3,2,4,5;
					Chemistry:5,5,4,3;
				}
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
